### ISSUE TITLE
Danalock v1

### ISSUE THREAD

**Issue by goyaweb** [athombv/com.danalock#1]
Doesn't work with Danalock v1.

**Comment by RobinBol** [comment]
V1 is Bluetooth only am I correct?

**Comment by goyaweb** [comment]
Nope I've got a z-wave version
		

		
	





On Thu, Apr 6, 2017 at 5:52 PM +0200, "Robin Bolscher" <notifications@github.com> wrote:












V1 is Bluetooth only am I correct?

**Comment by goyaweb** [comment]
Dit krijg ik als ik hem toevoeg als basic device:
![danalockbasic](https://cloud.githubusercontent.com/assets/783727/25072678/94c55bd2-22d5-11e7-852c-7178a10880b3.PNG)

**Comment by goyaweb** [comment]
Just sideloaded the app with as only change set the producttypeid to 3 instead of 8 and now I can include danalock v1. Locking and unlocking works just fine.

**Comment by RobinBol** [comment]
Oke thanks for the heads up, will add your productId to the app!

**Comment by goyaweb** [comment]
isn't:
"requireSecure": true
used to indicate a z-wave plus product?
Not sure what the impact is but danalock v1 is non-plus device.

**Comment by RobinBol** [comment]
But, the v1 is working for you right, with this flag?

**Comment by goyaweb** [comment]
yes
