### ISSUE TITLE
No Pairing possible V125

### ISSUE THREAD

**Issue by Sillec123** [athombv/com.danalock#4]

**Comment by RobinBol** [comment]
Could you provide some more info?

What happens when you try to pair it? Error messages?

**Comment by Sillec123** [comment]
Exchanging security key...

And than timeout!

**Comment by RobinBol** [comment]
Hi @Sillec123 is this still an issue for you? We have a Danalock at the office which pairs easily. My guess is that the distance between Homey and the lock was too big during pairing, or some other Z-Wave traffic disturbed the pairing process. Recommended distance when pairing is 30cm, it will likely work from larger distances, but this error is probably the result of a range issue during pairing (which needs a smaller range then normal operation).

**Comment by Sillec123** [comment]
The problem:
I have a different Product Type ID (you are using 8 but i have 3) Please add it for V125 V2  Manufacture ID: 270 Product Type ID: 3 Product ID: 2

**Comment by RobinBol** [comment]
Thanks, added your product type id (use the beta app in the app store). Please let know if the lock functions as expected!

**Comment by Sillec123** [comment]
ALlright, the device is paired but nothing happens if i try to lock or unlock the danalock. Strange with older version it was working. (i changed the id and side load the app, in the past.)

**Comment by RobinBol** [comment]
Strange, can you verify it is not a range issue? You can try to sideload the 'stable' version of the app with the added product type id, then I know it is the beta's fault or not.

**Comment by Sillec123** [comment]
I have a Fibaro relais 1m next to the dana lock and a motion sensor on the same door without any issues.

**Comment by RobinBol** [comment]
Did you try to side load the stable version?

**Comment by Sillec123** [comment]
@RobinBol 
yes, i can pair the device but the app is crashing:
TypeError: Cannot read property 'version' of undefined
at DanalockV2._getCapabilityObj (/node_modules/homey-meshdriver/lib/zwave/ZwaveDevice.js:346:52)
at DanalockV2._registerCapabilityRealtime (/node_modules/homey-meshdriver/lib/zwave/ZwaveDevice.js:274:36)
at DanalockV2.registerCapability (/node_modules/homey-meshdriver/lib/zwave/ZwaveDevice.js:423:8)
at DanalockV2.onMeshInit (/node_modules/homey-meshdriver/lib/zwave/ZwaveLockDevice.js:11:42)
at DanalockV2.once (/node_modules/homey-meshdriver/lib/zwave/ZwaveDevice.js:28:28)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:106:13)
at DanalockV2.emit (events.js:208:7)
at process.nextTick (/node_modules/homey-meshdriver/lib/MeshDevice.js:43:11)
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickCallback (internal/process/next_tick.js:180:9)

Exit code: 1
Exit signal: null

**Comment by Sillec123** [comment]
Both versions are not working. I tried it again with homey (power bar) directly next to dana lock.

**Comment by RobinBol** [comment]
Ok, the crash taught me that your device has a different z-wave implementation then the V2/V3, hence you can not use it with those drivers. Since the V125 is end-of-life (correct me if i'm wrong), we aren't going to support it. You can try the developer community, maybe someone has the same device and can create a driver for it!

**Comment by Sillec123** [comment]
But why was the old sdk 1 Version working? That doesn’t matter. The crash issue was that the z-wave driver was wrong. The device.js was without the methods. 

Diese E-Mail wurde von einem mobilen Gerät gesendet. Ich bitte Tippfehler zu entschuldigen. 

This mail was written on a mobile device. Thank you for understanding.

**Comment by RobinBol** [comment]
Not sure, can not verify that because we do not have the device. I don't know what you mean with 'device.js was without the methods'.
